### ISSUE TITLE
repl doesn't work in firefox

### ISSUE THREAD

**Issue by kpm** [yhara/biwascheme#14]
I recently tried the biwascheme repl in firefox.  The hello world sample code produces this error:

$(this.dumparea) is null

I have tried this in firefox 3.5 on windows, and firefox 3 on linux.

I remember that the previous time I tried it (a few months ago) it didn't work in firefox either, but it was ok in Internet Explorer.

**Comment by yhara** [comment]
Hi, 

thanks for reporting the issue!
I found that I forgot 'git pull' on the server.
It's working fine now: http://www.biwascheme.org/
