### ISSUE TITLE
there is no gensym function in scheme

### ISSUE THREAD

**Issue by jcubic** [yhara/biwascheme#16]
gensym implementation could look like this:

<pre><code>BiwaScheme.gensymcount = 0;
BiwaScheme.define_libfunc('gensym', 0, 0, function(args) {
    with(BiwaScheme) {
        return new Sym('#' + gensymcount++);
    }
});
</code></pre>

I've found that there is BiwaScheme.gensym function but it's not accessable from scheme.

<pre><code>BiwaScheme.define_libfunc('gensym', 0, 0, function(args) {
    return BiwaScheme.gensym();
}</code></pre>

**Comment by yhara** [comment]
Thanks for your comment (and for using BiwaScheme)!

Added (gensym) in this commit.
http://github.com/yhara/biwascheme/commit/28e1e0c3c87c140aca151343bba903d3561cf195
