### ISSUE TITLE
Broken pair detection for assoc, etc.

### ISSUE THREAD

**Issue by rpdillon** [yhara/biwascheme#27]
In line 14404 and 14421 of biwascheme.js, assoc checks for the presence of a pair by running x.car.car though an if(...) statement.  This presents a type 2 error in cases where the car of the pair is anything that would return false, like 0 or #f.
I fixed it in my tests by replacing:

```
if(x.car.car) {
 ...
}
```

with

```
if(typeof(x.car.car) != "undefined") {
 ...
}
```

**Comment by yhara** [comment]
Thanks! Fixed with this commit.
https://github.com/biwascheme/biwascheme/commit/237f4dacb6243b3150121cb2632b2f3ac83952eb
