### ISSUE TITLE
'list-ref' implementation bug

### ISSUE THREAD

**Issue by rpdillon** [yhara/biwascheme#28]
I think it affects more than just list-ref, but bounds checking is broken:

```
biwascheme> (list-ref (iota 9) 9)
[BUG] library function `list-ref' returned JavaScript's undefined
```

```
biwascheme> (list-ref (iota 9) 11)
d is undefined
```

In the most recent version, the error is the same, though the variable is named 'o' instead of 'd'.  These interactions were taken from the interpreter on biwascheme.org.

It's pretty clear what's causing this in the implementation -- it's just a case of some edge cases slipping through the implementation (returning x.cdr without checking if it is defined, for example).

**Comment by yhara** [comment]
Hi,

Thanks for reporting. Fixed by: https://github.com/biwascheme/biwascheme/commit/6d94364f31f34ee66723e4fc1752443a3f2f8484

The reason of this bug was "!o instance of Pair", which should be "!(o instance of Pair)".

**Comment by rpdillon** [comment]
Awesome.  Thanks for your great work in BiwaScheme...I'm using it in a couple of projects and I'm enjoying it.  Your responsiveness is really encouraging. =)

**Comment by yhara** [comment]
You're welsome. I'm happy to hear that :-)
