### ISSUE TITLE
cadr on list with 1 element.

### ISSUE THREAD

**Issue by dp-yp-mbg** [yhara/biwascheme#31]
When applying functions like  cadr to a list, for which it should not work (and raise the message "Error: Attempt to apply car on nil"), instead the result is "[BUG] library function `cadr' returned JavaScript's undefined". I guess this is a low-priority bug, since it presents itself only when the input is incorrect, but nevertheless I doubt it is what is expected.

The bug also appears when calling caddr and cadddr with similar examples.

Example:
   (cadr '(1))
[BUG] library function `cadr' returned JavaScript's undefined

Version is 0.5.7, as seen on repl.it

**Comment by yhara** [comment]
Yes, it should raise an error with better message. I will try fixing it.

**Comment by yhara** [comment]
Fixed! Thank you for reporting.
